spring:
  application:
    name: account-service
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            isolation.level: read_committed
        bindings:
          output:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        input:
          group: ${spring.application.name}
          destination: account
          contentType: application/*+avro
        inputFraudulent:
          group: ${spring.application.name}
          destination: fraudulent-transfer
          contentType: application/*+avro
      schema-registry-client:
        endpoint: http://localhost:8081
      schema:
        avro:
          subjectNamingStrategy: org.springframework.cloud.stream.schema.avro.QualifiedSubjectNamingStrategy
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
